name: Deploy to InfinityFree

on:
  push:
    branches:
      - main # Or 'master', whichever you use as your default branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📝 Replace DB Placeholders
        run: |
          sed -i "s|DB_USERNAME_PLACEHOLDER|${{ secrets.DB_USERNAME }}|g" db.php
          sed -i "s|DB_PASSWORD_PLACEHOLDER|${{ secrets.DB_PASSWORD }}|g" db.php
          sed -i "s|DB_HOST_PLACEHOLDER|${{ secrets.DB_HOST }}|g" db.php
          sed -i "s|DB_NAME_PLACEHOLDER|${{ secrets.DB_NAME }}|g" db.php

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/ # InfinityFree's default web directory
          # exclude: |
          #   **/.git*
          #   **/node_modules/**
          #   README.md
          #   docker-compose.yml
          #   Dockerfile
